### ISSUE TITLE
500 error for schedule-check-in

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#78]
Bought a flight for the future on points since it was a good deal, never received an email confirmation. Looking at the logs it got an error on schedule-check-in. Nothing helpful in the logs

```START RequestId: 144f297c-447a-4342-90d0-1ccc946a44dd Version: $LATEST
04:53:49 [INFO] 2020-04-25T04:53:49.951Z 144f297c-447a-4342-90d0-1ccc946a44dd Looking up reservation ABC123 for John Doe
04:53:50 status_code=500 msg="We are experiencing an issue with your request. Please try again in a few moments.": SouthwestAPIError Traceback (most recent call last): File "/var/task/handlers/schedule_check_in.py", line 35, in main first_name, last_name, confirmation_number File "/var/task/swa.py", line 72, in from_passenger_info params File "/var/task/swa.py", line 47, in _make_request
04:53:50 END RequestId: 144f297c-447a-4342-90d0-1ccc946a44dd

**Comment by DavidWittman** [comment]
Thanks for reporting this @ScottBishop... Should be fixed in master once #79 is merged.
