### ISSUE TITLE
API Authentication Errors: 429 Rate Limiting Error & 403 Forbidden

### ISSUE THREAD

**Issue by ScottBishop** [DavidWittman/serverless-southwest-check-in#83]
Check in lambda is failing due to 429 error - Too Many Requests. I don't have a lot of users, so I think this may be related to the API auth. 

```
status_code=429 msg="Error.": SouthwestAPIError Traceback (most recent call last): File "/var/task/handlers/check_in.py", line 40, in main resp = swa.check_in(first_name, last_name, confirmation_number) File "/var/task/swa.py", line 136, in check_in response = _make_request("post", page, body) File "/var/task/swa.py", line 48, in _make_request response.status_code, msg)) exceptions.SouthwestAPIError: status_code=429 msg="Error."
```

This may or may not be related -- schedule check in receives this error:

```
status_code=403 msg="Forbidden": SouthwestAPIError Traceback (most recent call last): File "/var/task/handlers/schedule_check_in.py", line 35, in main first_name, last_name, confirmation_number File "/var/task/swa.py", line 73, in from_passenger_info params File 
```

**Comment by DavidWittman** [comment]
Thanks Scott... They updated their API in the first week of August and it
broke all check-ins :(. The app is generating a unique token for each
request which doesn't seem easily reproducible.

**Comment by ScottBishop** [comment]
Have you been able to look into it? Do you know what changed?

Happy to help as well.

**Comment by DavidWittman** [comment]
Yeah, they now require a unique `X-Dublriiu-` header now which gets
generated client-side and sent with every check-in request. Not quite sure
how it gets generated... I'm assuming it isn't easy though.

Dave

**Comment by mastermind85** [comment]
Looks like this one fixed the API, are you able to leverage the changes they made? https://github.com/mwynholds/southy

**Comment by ScottBishop** [comment]
I tested it out with their API Key and User Agent, still see the 429 error, they still aren't using the `X-Dublriiu-` header

```
status_code=429 msg="Error.": SouthwestAPIError
Traceback (most recent call last):
  File "/var/task/handlers/check_in.py", line 40, in main
    resp = swa.check_in(first_name, last_name, confirmation_number)
  File "/var/task/swa.py", line 136, in check_in
    response = _make_request("post", page, body)
  File "/var/task/swa.py", line 48, in _make_request
    response.status_code, msg))
exceptions.SouthwestAPIError: status_code=429 msg="Error."

**Comment by DavidWittman** [comment]
@ScottBishop @mastermind85 I'm testing some changes in #84 to resolve this. If either of y'all happen to have some upcoming flights I can test it on let me know.

**Comment by ScottBishop** [comment]
I have a friend with a flight tomorrow, just sent you the details to the email listed on your github page.
